#!/bin/bash

############################################
# name: kill-auto-connect
# version: 0.1
# authors: Cristian Sottile, Bruno Cascio
############################################

# Mato el proceso auto-connect.sh

id=$(ps aux | grep -v grep | grep auto-connect.sh | tr -s ' ' , | cut -d',' -f2)

kill -9 $id

exit 0
